// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dmwwyupwapayfdnftmjw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRtd3d5dXB3YXBheWZkbmZ0bWp3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzNTgyODAsImV4cCI6MjA2MzkzNDI4MH0.9RRd5KB5AA090aBVa-5DpvIxCNA0ljY3wwELYz91rfY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);